<a href="https://colab.research.google.com/github/puraminy/mini_proj2/blob/master/BAM2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [161]:
import numpy as np

A = [-1, 1, -1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1]
tA = [-1, -1,-1] #tA = np.asmatrix([-1, 1]
B = [1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, 1, 1, -1]
tB = [-1, -1, 1]
C = [-1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, -1, -1, 1, 1]
tC = [-1,1,-1] #tC = np.asmatrix([1, 1])
D = [1, 1, -1, 1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, -1]
tD = [-1,1,1]
E = [1, 1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, 1]
tE = [1,-1,-1]
F =[1, 1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, 1, -1, -1]
tF = [1, -1, 1]
G = [-1, 1, 1, 1, -1, -1, 1, -1, 1, 1, -1, 1, -1, 1, 1]
tG = [1, 1, -1]
H = [1, -1, 1, 1, -1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1]
tH = [1, 1, 1]

X =[A,B,C,D,E,F,G,H]
#print(X)
Y = [tA,tB,tC,tD,tE,tF,tG,tH]
#print(Y)
#W = np.matmul(np.transpose(np.expand_dims(A, axis = 0)),tA) #+ np.matmul(np.transpose(C),tC)
#print(W)
#print(np.transpose(W))
#X.shape
#Y.shape
#A.shape
pair = []
for i in range (8):
  pair.append([X[i], Y[i]])
  
pair[1]


[[1, 1, -1, 1, -1, 1, 1, 1, -1, 1, -1, 1, 1, 1, -1], [-1, -1, 1]]

In [162]:
IN = np.asarray(A)
x = np.expand_dims(IN, axis = 0)
y = np.sign(np.matmul(x,W)) 
x_out = np.sign(np.matmul(y, np.transpose(W)))
#x_out[0,2]=3
print (x)
print (x_out)
np.max((x - x_out)) !=0 or np.min((x - x_out)) !=0

[[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]]
[[ 1.  1. -1.  0.  0.  1.  0.  1. -1.  0.  0.  1.  1. -1. -1.]]


True

In [156]:
def BAM1(X,Y):
  X = np.asarray(X)
  Y = np.asarray(Y)
  n,m1 = X.shape
  n,m2 = Y.shape
  W=np.zeros([m1,m2])
  for i in range(n):
    W =W + np.matmul(np.transpose(np.asmatrix(X[i,:])),np.asmatrix(Y[i,:]))
  
  return W

W = BAM1(X,Y)
W


matrix([[ 2., -2.,  6.],
        [-2., -2., -2.],
        [ 6.,  2., -2.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [-4.,  0.,  4.],
        [ 0.,  0.,  0.],
        [ 2., -6.,  2.],
        [ 0.,  4.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [-2.,  2.,  2.],
        [ 0., -4.,  4.],
        [-2.,  2., -2.],
        [ 2.,  2., -6.]])

In [160]:
def BAM2(W, IN):
  IN = np.asarray(IN)
  m,n = W.shape
  if IN.shape == (m,):
    W = W
  elif IN.shape == (n,):
    W = np.transpose(W)
  
  x = np.expand_dims(IN, axis = 0)
  y = np.sign(np.matmul(x,W)) 
  x_out = np.sign(np.matmul(y, np.transpose(W)))
  while np.max((x - x_out)) !=0 or np.min((x - x_out)) !=0:
    x = x_out 
    y = np.sign(np.matmul(x,W))
    x_out = np.sign(np.matmul(y, np.transpose(W)))
  return y, x

y,x = BAM2(W, E)
print (y,x)

[[ 1. -1. -1.]] [[-1.  1.  1.  0.  0. -1.  0.  1. -1.  0.  0. -1.  0. -1.  1.]]
